---
- hosts: all
  name: Setup Docker
  tasks:
  - name: Check Docker version
    shell: >
      docker info --format \{\{.ServerVersion\}\} || true
    register: docker_version

  - name: Plan Docker install
    add_host:
      hostname: "{{ item }}"
      groups: docker_install
    with_items: "{{ ansible_play_hosts }}"
    when: docker_version.stdout | length == 0
    run_once: true

- name: Install Docker
  hosts: docker_install
  become: true
  tasks:
  - name: Install required system packages
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      state: latest
      update_cache: yes

  - name: Add docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
      state: present

  - name: Add docker apt repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
      filename: docker-stable
      update_cache: no
      state: present

  - name: Install docker-ce
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
      update_cache: yes

  - name: Ensure Docker service is started and enabled
    service:
      name: docker
      state: started
      enabled: true

  - name: Ensure current user is added to the docker group
    user:
      name: "{{ ansible_user }}"
      append: yes
      groups:
      - docker
